export const FETCH_NOTES_REQUESTED = 'FETCH_NOTES_REQUESTED';
export type FETCH_NOTES_REQUESTED = typeof FETCH_NOTES_REQUESTED;

export const DELETE_NOTE = 'DELETE_NOTE';
export type DELETE_NOTE = typeof DELETE_NOTE;

export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export type FETCH_NOTES_SUCCESS = typeof FETCH_NOTES_SUCCESS;

export const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR';
export type FETCH_NOTES_ERROR = typeof FETCH_NOTES_ERROR;